name: to_do_app
description: "A new Flutter project."
publish_to: 'none'
version: 0.1.0

environment:
  sdk: ^3.7.2

dependencies:
  intl: ^0.18.0
  flutter:
    sdk: flutter
  json_annotation: ^4.8.0
  provider: ^6.1.5
  shared_preferences: ^2.5.3
  get: ^4.3.8
  flutter_local_notifications: ^14.1.1
  flutter_timezone: ^1.0.8
  flutter_staggered_animations: ^1.0.0
  flutter_svg: ^2.0.7
  rxdart: ^0.27.2
  timezone: ^0.9.2

  go_router: ^6.2.0
  uuid: ^4.3.3
  image_picker: ^1.0.7
  google_fonts: ^6.2.1

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0
  json_serializable: ^6.9.5
  build_runner: ^2.3.3
  flutter_launcher_icons: ^0.13.1

flutter_icons:
  android: true
  ios: true
  image_path: "images/icon.jpg"


flutter:
  uses-material-design: true
